# Generated by Django 3.0.1 on 2020-01-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Outline'),
        ),
    ]
