# Generated by Django 3.0.1 on 2020-01-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200104_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/media/profile.jpg', upload_to='static/media/'),
        ),
    ]
